*** Comments ***
Phase 3: Node A reads a GPS receiver (NMEA on UART4), computes its heading from
the magnetometer, and stops using the magnetometer when its field is disturbed,
as near a loaded power line (HLR-008, HLR-010).

Magnetometer values are set as the Renode model's properties, divided by the
model's gain of 1.147 (see node_a_imu.robot), so the firmware reads the field
in the comments. For level flight at a true heading of 60 degrees in the
expected local field (500 mG, dip 56 degrees, declination 5 degrees east), the
body-axis field is (160, 229, -415) mG.

Run from the repository root (inside WSL):
    renode-test tests/robot/node_a_nav.robot


*** Settings ***
Resource            ${RENODEKEYWORDS}

Suite Setup         Setup
Suite Teardown      Teardown
Test Setup          Reset Emulation
Test Teardown       Test Teardown


*** Variables ***
${ROOT}             ${CURDIR}/../..
${ELF}              ${ROOT}/build/debug/firmware/node_a/node_a.elf
${MAG}              sysbus.i2c1.mag
# Generated by the plant's GPS model (sim/plant/nmea.py).
${GGA}              $GPGGA,100001.50,3954.00000,N,03248.00000,E,1,09,0.9,925.0,M,36.0,M,,*64
${RMC}              $GPRMC,100001.50,A,3954.00000,N,03248.00000,E,10.00,90.0,091026,,,A*69
${BAD_GGA}          $GPGGA,100001.50,3954.00000,N,03248.00000,E,1,09,0.9,925.0,M,36.0,M,,*65


*** Keywords ***
Create Node A
    Execute Command    $bin_a=@${ELF}
    Execute Command    include @${ROOT}/renode/node_a.resc
    ${console}=    Create Terminal Tester    sysbus.usart2    defaultPauseEmulation=True
    ${gps}=    Create Terminal Tester    sysbus.uart4    defaultPauseEmulation=True
    Set Test Variable    ${CONSOLE}    ${console}
    Set Test Variable    ${GPS}    ${gps}
    # Level: the accelerometer shows 1 g up.
    Execute Command    sysbus.i2c1.imu AccelerationZ 1
    Wait For Line On Uart    gps: listening on UART4    testerId=${CONSOLE}

Send Gps
    [Arguments]    @{sentences}
    FOR    ${sentence}    IN    @{sentences}
        Write Line To Uart    ${sentence}    testerId=${GPS}    waitForEcho=False
    END

Set Field
    [Arguments]    ${x}    ${y}    ${z}
    Execute Command    ${MAG} MagneticX ${x}
    Execute Command    ${MAG} MagneticY ${y}
    Execute Command    ${MAG} MagneticZ ${z}

Set Undisturbed Field
    Set Field    0.13983    0.1997    -0.36143

Set Disturbed Field
    # 30 % stronger, as close to a conductor: (208, 298, -539) mG.
    Set Field    0.18178    0.25961    -0.46986

Expect Console
    [Arguments]    ${text}    ${timeout}=2    ${regex}=false
    Wait For Line On Uart    ${text}    testerId=${CONSOLE}    timeout=${timeout}    treatAsRegex=${regex}


*** Test Cases ***
Should Report No Fix Without A Gps
    Create Node A
    Expect Console    gps: no fix (0 sentences/s)

Should Parse A Gps Fix
    Create Node A
    Send Gps    ${GGA}    ${RMC}
    Expect Console    gps: 2 sentences/s, fix q1 sats 9, lat 39.9000000 lon 32.8000000 alt 92500 cm, 514 cm/s course 9000 cdeg

Should Count A Corrupted Gps Sentence
    Create Node A
    Send Gps    ${BAD_GGA}
    Expect Console    gps: 1 bad sentences, last CHECKSUM

Should Compute The Magnetometer Heading
    Create Node A
    Set Undisturbed Field
    Expect Console    nav: heading (599\\d|600\\d) cdeg from magnetometer, field (499|50[01]) mG, dip (559\\d|560\\d) cdeg, magnetometer ok    regex=true

Should Stop Using A Disturbed Magnetometer And Recover
    Create Node A
    Set Undisturbed Field
    Expect Console    magnetometer ok
    Set Disturbed Field
    Expect Console    nav: magnetometer disturbed
    # No GPS course either, so there is no heading.
    Expect Console    from none, field 6\\d\\d mG, .* magnetometer DISTURBED    regex=true
    Set Undisturbed Field
    # One second of clean samples is needed to trust it again.
    Expect Console    nav: magnetometer field back within limits    timeout=1.5
    Expect Console    from magnetometer, field (499|50[01]) mG    regex=true

Should Fall Back To The Gps Course
    Create Node A
    Set Disturbed Field
    Expect Console    nav: magnetometer disturbed
    Expect Console    heartbeat 1
    # RMC: 10 knots on a course of 90 degrees.
    Send Gps    ${GGA}    ${RMC}
    Expect Console    nav: heading 9000 cdeg from GPS course
