#!/usr/bin/env bash
# Vendors the part of TensorFlow Lite Micro that Node A uses into third_party/tflite-micro.
#
# TFLM is distributed as a source tree generated from its repository
# (create_tflm_tree.py downloads and patches flatbuffers, among others). Node A
# needs the interpreter and two reference kernels (FULLY_CONNECTED, SOFTMAX), so
# only those sources and the headers they include are copied, with the licences.
# The source list was found by linking Node A's model wrapper against the
# whole tree and keeping the archive members the linker pulled in.
#
# Usage (Linux/WSL, from the repository root; needs git, python3, arm-none-eabi-g++):
#     bash tools/tflm/vendor.sh
set -euo pipefail

TFLM_URL="https://github.com/tensorflow/tflite-micro.git"
TFLM_COMMIT="230c9d9531bd9b08d445b4f2ed0760756ffd5f78"

SOURCES=(
    tensorflow/lite/micro/arena_allocator/non_persistent_arena_buffer_allocator.cc
    tensorflow/lite/micro/arena_allocator/persistent_arena_buffer_allocator.cc
    tensorflow/lite/micro/arena_allocator/single_arena_buffer_allocator.cc
    tensorflow/lite/micro/flatbuffer_conversions.cc
    tensorflow/lite/micro/flatbuffer_utils.cc
    tensorflow/lite/micro/kernels/fully_connected.cc
    tensorflow/lite/micro/kernels/fully_connected_common.cc
    tensorflow/lite/micro/kernels/internal/common.cc
    tensorflow/lite/micro/kernels/internal/portable_tensor_utils.cc
    tensorflow/lite/micro/kernels/internal/quantization_util.cc
    tensorflow/lite/micro/kernels/internal/tensor_ctypes.cc
    tensorflow/lite/micro/kernels/kernel_util.cc
    tensorflow/lite/micro/kernels/softmax.cc
    tensorflow/lite/micro/kernels/softmax_common.cc
    tensorflow/lite/micro/memory_helpers.cc
    tensorflow/lite/micro/memory_planner/greedy_memory_planner.cc
    tensorflow/lite/micro/memory_planner/linear_memory_planner.cc
    tensorflow/lite/micro/micro_allocation_info.cc
    tensorflow/lite/micro/micro_allocator.cc
    tensorflow/lite/micro/micro_common.cc
    tensorflow/lite/micro/micro_context.cc
    tensorflow/lite/micro/micro_interpreter.cc
    tensorflow/lite/micro/micro_interpreter_context.cc
    tensorflow/lite/micro/micro_interpreter_graph.cc
    tensorflow/lite/micro/micro_log.cc
    tensorflow/lite/micro/micro_op_resolver.cc
    tensorflow/lite/micro/micro_resource_variable.cc
    tensorflow/lite/micro/micro_utils.cc
)

# Headers our own code includes (vib_model.cc, tflm_port.cc).
ENTRY_HEADERS=(
    tensorflow/lite/micro/micro_interpreter.h
    tensorflow/lite/micro/micro_mutable_op_resolver.h
    tensorflow/lite/schema/schema_generated.h
    tensorflow/lite/micro/debug_log.h
)

REPO="$(cd "$(dirname "$0")/../.." && pwd)"
DEST="$REPO/third_party/tflite-micro"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

git clone --quiet --filter=blob:none "$TFLM_URL" "$WORK/src"
git -C "$WORK/src" checkout --quiet "$TFLM_COMMIT"
# The generator runs TFLM's Makefile, so it must start in the checkout.
(cd "$WORK/src" && python3 tensorflow/lite/micro/tools/project_generation/create_tflm_tree.py \
    --makefile_options="TARGET=cortex_m_generic TARGET_ARCH=cortex-m4+fp" "$WORK/tree" > /dev/null)
TREE="$WORK/tree"

# Every header the sources and entry headers include, found by the compiler itself.
FLAGS=(-std=c++17 -DTF_LITE_STATIC_MEMORY -I"$TREE" -I"$TREE/third_party/flatbuffers/include")
FILES=("${SOURCES[@]}")
for f in "${SOURCES[@]}" "${ENTRY_HEADERS[@]}"; do
    deps="$(cd "$TREE" && arm-none-eabi-g++ "${FLAGS[@]}" -x c++ -MM "$f" | sed 's/^[^:]*://; s/\\$//')"
    for d in $deps; do
        FILES+=("${d#"$TREE"/}")
    done
done

rm -rf "$DEST"
mkdir -p "$DEST"
printf '%s\n' "${FILES[@]}" | sort -u | while read -r f; do
    mkdir -p "$DEST/$(dirname "$f")"
    cp "$TREE/$f" "$DEST/$f"
done
cp "$TREE/LICENSE" "$DEST/LICENSE"
cp "$TREE/third_party/flatbuffers/LICENSE" "$DEST/third_party/flatbuffers/LICENSE"
printf '%s\n' "${SOURCES[@]}" > "$DEST/sources.txt"

cat > "$DEST/README.md" <<EOF
# TensorFlow Lite Micro (vendored subset)

The part of [TensorFlow Lite Micro](https://github.com/tensorflow/tflite-micro) that
Node A's vibration classifier uses: the interpreter, the memory planners and the
reference FULLY_CONNECTED and SOFTMAX kernels, with the flatbuffers headers
(as patched by TFLM). Generated by \`tools/tflm/vendor.sh\` from commit
\`$TFLM_COMMIT\`; do not edit, re-run the script instead.

- \`sources.txt\` lists the files that are compiled (\`firmware/node_a/CMakeLists.txt\`).
- Licences: Apache 2.0 for TFLM (\`LICENSE\`) and for flatbuffers
  (\`third_party/flatbuffers/LICENSE\`).
EOF

echo "vendored $(printf '%s\n' "${FILES[@]}" | sort -u | wc -l) files from TFLM $TFLM_COMMIT into $DEST"
