/**
 * @file vib_model_data.h
 * @brief The INT8 vibration classifier as a TFLite flatbuffer.
 *
 * Generated by ml/train.py; do not edit.
 */
#ifndef VIB_MODEL_DATA_H
#define VIB_MODEL_DATA_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

extern const uint8_t vib_model_data[];
extern const uint32_t vib_model_data_len;

#ifdef __cplusplus
}
#endif

#endif /* VIB_MODEL_DATA_H */
