/**
 * @file vib_model.h
 * @brief The INT8 vibration classifier, run with TensorFlow Lite Micro (HLR-009).
 *
 * A C interface to the C++ interpreter (vib_model.cc). The model
 * (vib_model_data.c, generated by ml/train.py) takes the VIB_FEATURES
 * features of one window, quantised to int8, and returns one int8 score per
 * class (vib_class_t), which dequantises to the class probability.
 *
 * Everything is statically allocated: the interpreter, the op resolver (two
 * kernels: FULLY_CONNECTED and SOFTMAX) and the tensor arena. Not reentrant:
 * only AiTask calls these functions, after vib_model_init().
 */
#ifndef VIB_MODEL_H
#define VIB_MODEL_H

#include <stdbool.h>
#include <stdint.h>

#include "vib_alarm.h"
#include "vib_features.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Loads the model, checks its version and tensor shapes and types, and
 * allocates the tensors. Returns false (and logs why) if it cannot be used.
 */
bool vib_model_init(void);

/** Quantises features with the input tensor's scale and zero point (round half away from zero). */
void vib_model_quantise(const float features[VIB_FEATURES], int8_t input[VIB_FEATURES]);

/** Runs one inference. Returns false if the model is not ready or the interpreter failed. */
bool vib_model_run(const int8_t input[VIB_FEATURES], int8_t output[VIB_CLASS_COUNT]);

/** Dequantises one output score to a probability (0..1). */
float vib_model_probability(int8_t score);

/** Bytes of the tensor arena the model uses (after vib_model_init()). */
uint32_t vib_model_arena_used(void);

#ifdef __cplusplus
}
#endif

#endif /* VIB_MODEL_H */
